//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diplom.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add in Group.
        /// </summary>
        public static string DataTableActionsAddToolsGroup {
            get {
                return ResourceManager.GetString("DataTableActionsAddToolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string DataTableActionsDeactivate {
            get {
                return ResourceManager.GetString("DataTableActionsDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DataTableActionsDelete {
            get {
                return ResourceManager.GetString("DataTableActionsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DataTableActionsEdit {
            get {
                return ResourceManager.GetString("DataTableActionsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DataTableActionsView {
            get {
                return ResourceManager.GetString("DataTableActionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string DataTableHederTextAction {
            get {
                return ResourceManager.GetString("DataTableHederTextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string DataTableHederTextBrand {
            get {
                return ResourceManager.GetString("DataTableHederTextBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string DataTableHederTextCategory {
            get {
                return ResourceManager.GetString("DataTableHederTextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DataTableHederTextDate {
            get {
                return ResourceManager.GetString("DataTableHederTextDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string DataTableHederTextImage {
            get {
                return ResourceManager.GetString("DataTableHederTextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string DataTableHederTextModel {
            get {
                return ResourceManager.GetString("DataTableHederTextModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataTableHederTextName {
            get {
                return ResourceManager.GetString("DataTableHederTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string DataTableHederTextUserName {
            get {
                return ResourceManager.GetString("DataTableHederTextUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string DataTableHederTextUserRole {
            get {
                return ResourceManager.GetString("DataTableHederTextUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string DataTablesEmptyTable {
            get {
                return ResourceManager.GetString("DataTablesEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string DataTablesFirst {
            get {
                return ResourceManager.GetString("DataTablesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string DataTablesInfo {
            get {
                return ResourceManager.GetString("DataTablesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string DataTablesInfoEmpty {
            get {
                return ResourceManager.GetString("DataTablesInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string DataTablesInfoFiltered {
            get {
                return ResourceManager.GetString("DataTablesInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataTablesInfoPostFix {
            get {
                return ResourceManager.GetString("DataTablesInfoPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string DataTablesInfoThousands {
            get {
                return ResourceManager.GetString("DataTablesInfoThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string DataTablesLast {
            get {
                return ResourceManager.GetString("DataTablesLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string DataTablesLengthMenu {
            get {
                return ResourceManager.GetString("DataTablesLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string DataTablesLoadingRecords {
            get {
                return ResourceManager.GetString("DataTablesLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DataTablesNext {
            get {
                return ResourceManager.GetString("DataTablesNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string DataTablesPrevious {
            get {
                return ResourceManager.GetString("DataTablesPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string DataTablesProcessing {
            get {
                return ResourceManager.GetString("DataTablesProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string DataTablesSearch {
            get {
                return ResourceManager.GetString("DataTablesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column ascending.
        /// </summary>
        public static string DataTablesSortAscending {
            get {
                return ResourceManager.GetString("DataTablesSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column descending.
        /// </summary>
        public static string DataTablesSortDescending {
            get {
                return ResourceManager.GetString("DataTablesSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string DataTablesZeroRecords {
            get {
                return ResourceManager.GetString("DataTablesZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Value.
        /// </summary>
        public static string DropDownListSelectValue {
            get {
                return ResourceManager.GetString("DropDownListSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string HeaderChangeLanguageEnglish {
            get {
                return ResourceManager.GetString("HeaderChangeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string HeaderChangeLanguageRussian {
            get {
                return ResourceManager.GetString("HeaderChangeLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string HeaderChangeLanguageText {
            get {
                return ResourceManager.GetString("HeaderChangeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for something....
        /// </summary>
        public static string HeaderSearchPlaceholder {
            get {
                return ResourceManager.GetString("HeaderSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department was founded in 1961, is one of the earliest and leading departments in Ukraine for training specialists (programmers, system programmers, system administrators) in the field of computer systems and networks, software and hardware of computers, specialized computer systems, including health care and medical institutions. Training is conducted in conjunction with leading software developers in Ukraine to set out the latest technology to create a modern software development and implementation of [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeAbout {
            get {
                return ResourceManager.GetString("HomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeAboutLink {
            get {
                return ResourceManager.GetString("HomeAboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer systems and networks.
        /// </summary>
        public static string HomeComputerSystem {
            get {
                return ResourceManager.GetString("HomeComputerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education was opened in 1961. It is possible to budget and contract training for full-time and part-time form ...
        /// </summary>
        public static string HomeComputerSystemDescription {
            get {
                return ResourceManager.GetString("HomeComputerSystemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Reading.
        /// </summary>
        public static string HomeContinueReading {
            get {
                return ResourceManager.GetString("HomeContinueReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Department:.
        /// </summary>
        public static string HomeHeadofDepartment {
            get {
                return ResourceManager.GetString("HomeHeadofDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string HomeLinkAccount {
            get {
                return ResourceManager.GetString("HomeLinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string HomeLinkProfile {
            get {
                return ResourceManager.GetString("HomeLinkProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administration.
        /// </summary>
        public static string HomeLinkSystemAdministration {
            get {
                return ResourceManager.GetString("HomeLinkSystemAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string HomeLogoText {
            get {
                return ResourceManager.GetString("HomeLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string HomeMenuLink {
            get {
                return ResourceManager.GetString("HomeMenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string HomeNewsLink {
            get {
                return ResourceManager.GetString("HomeNewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department trains specialists in the following areas.
        /// </summary>
        public static string HomeProduceP {
            get {
                return ResourceManager.GetString("HomeProduceP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce special and specialization.
        /// </summary>
        public static string HomeProduceTitle {
            get {
                return ResourceManager.GetString("HomeProduceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Technical University.
        /// </summary>
        public static string HomeSmallTitle {
            get {
                return ResourceManager.GetString("HomeSmallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Kharkiv Polytechnic Institute&quot;.
        /// </summary>
        public static string HomeSmallTitleLink {
            get {
                return ResourceManager.GetString("HomeSmallTitleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized computer systems.
        /// </summary>
        public static string HomeSpecializedComputerSystems {
            get {
                return ResourceManager.GetString("HomeSpecializedComputerSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function was discovered in 1991 year. It is possible to budget and contract training full-time ...
        /// </summary>
        public static string HomeSpecializedComputerSystemsDescription {
            get {
                return ResourceManager.GetString("HomeSpecializedComputerSystemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Programming.
        /// </summary>
        public static string HomeSystemProgramming {
            get {
                return ResourceManager.GetString("HomeSystemProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education was opened in 1961. It is possible to budget and contract training for full-time and part-time form ...
        /// </summary>
        public static string HomeSystemProgrammingDescription {
            get {
                return ResourceManager.GetString("HomeSystemProgrammingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Computer Engineering and Programming&quot;.
        /// </summary>
        public static string HomeTitleLink {
            get {
                return ResourceManager.GetString("HomeTitleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.kpi.kharkov.ua/layout/images/lang/en.png.
        /// </summary>
        public static string LanguageIconLink {
            get {
                return ResourceManager.GetString("LanguageIconLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string LanguageShortName {
            get {
                return ResourceManager.GetString("LanguageShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LoginFormLoginBtn {
            get {
                return ResourceManager.GetString("LoginFormLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginFormPassword {
            get {
                return ResourceManager.GetString("LoginFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string LoginFormRememberMe {
            get {
                return ResourceManager.GetString("LoginFormRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Login page.
        /// </summary>
        public static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User Name or Password.
        /// </summary>
        public static string LoginFormUnknownLogin {
            get {
                return ResourceManager.GetString("LoginFormUnknownLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LoginFormUserName {
            get {
                return ResourceManager.GetString("LoginFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LoginPartialLogOut {
            get {
                return ResourceManager.GetString("LoginPartialLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string LoginPartialSignIn {
            get {
                return ResourceManager.GetString("LoginPartialSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string ModalDeactivateConfirmationDeactivateBtn {
            get {
                return ResourceManager.GetString("ModalDeactivateConfirmationDeactivateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to diactivate one track..
        /// </summary>
        public static string ModalDeactivateConfirmationMessage {
            get {
                return ResourceManager.GetString("ModalDeactivateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        public static string ModalDeactivateConfirmationQuestion {
            get {
                return ResourceManager.GetString("ModalDeactivateConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deactivate.
        /// </summary>
        public static string ModalDeactivateConfirmationTitle {
            get {
                return ResourceManager.GetString("ModalDeactivateConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalDeleteConfirmationCancelBtn {
            get {
                return ResourceManager.GetString("ModalDeleteConfirmationCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ModalDeleteConfirmationDeleteBtn {
            get {
                return ResourceManager.GetString("ModalDeleteConfirmationDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete one track, this procedure is irreversible..
        /// </summary>
        public static string ModalDeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("ModalDeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        public static string ModalDeleteConfirmationQuestion {
            get {
                return ResourceManager.GetString("ModalDeleteConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ModalDeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("ModalDeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ProfileAbout {
            get {
                return ResourceManager.GetString("ProfileAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Degree.
        /// </summary>
        public static string ProfileAcademicDegree {
            get {
                return ResourceManager.GetString("ProfileAcademicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to friends.
        /// </summary>
        public static string ProfileAddToFriends {
            get {
                return ResourceManager.GetString("ProfileAddToFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string ProfileBasicInformation {
            get {
                return ResourceManager.GetString("ProfileBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string ProfileBitrthday {
            get {
                return ResourceManager.GetString("ProfileBitrthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProfileCancel {
            get {
                return ResourceManager.GetString("ProfileCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ProfileConnected {
            get {
                return ResourceManager.GetString("ProfileConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ProfileConnections {
            get {
                return ResourceManager.GetString("ProfileConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ProfileContacts {
            get {
                return ResourceManager.GetString("ProfileContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from friends.
        /// </summary>
        public static string ProfileDeleteFromFriends {
            get {
                return ResourceManager.GetString("ProfileDeleteFromFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string ProfileDiscipline {
            get {
                return ResourceManager.GetString("ProfileDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ProfileFullName {
            get {
                return ResourceManager.GetString("ProfileFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string ProfileGender {
            get {
                return ResourceManager.GetString("ProfileGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Scientific Title.
        /// </summary>
        public static string ProfileInfoScientificTitle {
            get {
                return ResourceManager.GetString("ProfileInfoScientificTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string ProfileMobilePhone {
            get {
                return ResourceManager.GetString("ProfileMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string ProfilePatronymic {
            get {
                return ResourceManager.GetString("ProfilePatronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string ProfilePhotos {
            get {
                return ResourceManager.GetString("ProfilePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string ProfilePost {
            get {
                return ResourceManager.GetString("ProfilePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject subscription.
        /// </summary>
        public static string ProfileRejectSubscription {
            get {
                return ResourceManager.GetString("ProfileRejectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ProfileSave {
            get {
                return ResourceManager.GetString("ProfileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Interests.
        /// </summary>
        public static string ProfileScientificInterests {
            get {
                return ResourceManager.GetString("ProfileScientificInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Title.
        /// </summary>
        public static string ProfileScientificTitle {
            get {
                return ResourceManager.GetString("ProfileScientificTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string ProfileSkype {
            get {
                return ResourceManager.GetString("ProfileSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string ProfileSubscribers {
            get {
                return ResourceManager.GetString("ProfileSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string ProfileSubscriptions {
            get {
                return ResourceManager.GetString("ProfileSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher information.
        /// </summary>
        public static string ProfileTeacherInformation {
            get {
                return ResourceManager.GetString("ProfileTeacherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string ProfileTimeline {
            get {
                return ResourceManager.GetString("ProfileTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Connections.
        /// </summary>
        public static string ProfileTotalConnections {
            get {
                return ResourceManager.GetString("ProfileTotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Picture.
        /// </summary>
        public static string ProfileUpdateProfilePicture {
            get {
                return ResourceManager.GetString("ProfileUpdateProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string RegisterFormBirthDate {
            get {
                return ResourceManager.GetString("RegisterFormBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Password.
        /// </summary>
        public static string RegisterFormConfirmedPassword {
            get {
                return ResourceManager.GetString("RegisterFormConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterFormEmail {
            get {
                return ResourceManager.GetString("RegisterFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName has already exist.
        /// </summary>
        public static string RegisterFormError {
            get {
                return ResourceManager.GetString("RegisterFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string RegisterFormFemale {
            get {
                return ResourceManager.GetString("RegisterFormFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string RegisterFormFirstName {
            get {
                return ResourceManager.GetString("RegisterFormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string RegisterFormLastName {
            get {
                return ResourceManager.GetString("RegisterFormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string RegisterFormLoginBtn {
            get {
                return ResourceManager.GetString("RegisterFormLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string RegisterFormMale {
            get {
                return ResourceManager.GetString("RegisterFormMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterFormPassword {
            get {
                return ResourceManager.GetString("RegisterFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RegisterFormRememberMe {
            get {
                return ResourceManager.GetString("RegisterFormRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Register page.
        /// </summary>
        public static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string RegisterFormUserName {
            get {
                return ResourceManager.GetString("RegisterFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserActionLink {
            get {
                return ResourceManager.GetString("UserActionLink", resourceCulture);
            }
        }
    }
}
